In [1]:
import pandas as pd

Create an empty DataFrame

In [2]:

df=pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []

Create a DataFrame using List:

In [3]:
l=[101,3,15,17,18]

df=pd.DataFrame(l,index=['A','B','C','D','E'])

print(df)

     0
A  101
B    3
C   15
D   17
E   18

Create a DataFrame from Dict of ndarrays/ Lists

In [4]:
l={'id':[1,2,3],'name':['haresh','shailesh','mohit']} 
 
df = pd.DataFrame(l)   
print (df)

   id      name
0   1    haresh
1   2  shailesh
2   3     mohit

Create a DataFrame from Dict of Series:

In [5]:
ans=({'design':pd.Series([1,2,3],index=['a','b','c']),'development':pd.Series([4,5,6],index=['a','b','c'])})

rs=pd.DataFrame(ans)

print(rs)

   design  development
a       1            4
b       2            5
c       3            6

We can select any column from the DataFrame

In [6]:
ans=({'design':pd.Series([1,2,3],index=['a','b','c']),'development':pd.Series([4,5,6],index=['a','b','c'])})

rs=pd.DataFrame(ans)

# print(rs['design'])
print(rs['development'])

a    4
b    5
c    6
Name: development, dtype: int64

Column Addition

In [7]:
ans=({'design':pd.Series([1,2,3],index=['a','b','c']),'development':pd.Series([4,5,6],index=['a','b','c'])})

rs=pd.DataFrame(ans)

rs['skills']=pd.Series([20,30,60],index=['a','b','c'])

print(rs)

   design  development  skills
a       1            4      20
b       2            5      30
c       3            6      60

sum of column

In [8]:
ans=({'design':pd.Series([1,2,3],index=['a','b','c']),'development':pd.Series([4,5,6],index=['a','b','c'])})

rs=pd.DataFrame(ans)

rs['skills']=pd.Series([20,30,60],index=['a','b','c'])

print(rs['skills']+ rs['development'])

a    24
b    35
c    66
dtype: int64

Column Deletion:

In [9]:
ans=({'design':pd.Series([1,2,3],index=['a','b','c']),'development':pd.Series([4,5,6],index=['a','b','c'])})

rs=pd.DataFrame(ans)

rs['skills']=pd.Series([20,30,60],index=['a','b','c'])

print(rs['skills']+ rs['development'])

del rs['design']
print(rs)



# rs.pop('design')

a    24
b    35
c    66
dtype: int64
   development  skills
a            4      20
b            5      30
c            6      60

Row Selection, Addition, and Deletion

In [10]:
ans=({'design':pd.Series([1,2,3],index=['a','b','c']),'development':pd.Series([4,5,6],index=['a','b','c'])})

rs=pd.DataFrame(ans)

rs['skills']=pd.Series([20,30,60],index=['a','b','c'])

#addition
print(rs['skills']+ rs['development'])

#deletion
# del rs['design']
print(rs)

#selection single row   
print(rs.loc['a'])

#select single column
print(rs.loc['a':'b','development'])

#Select Multiple rows
print(rs.loc[['a','c']])

#Select Multiple columns 
print(rs.loc[:,['development','skills']])

#Select row range 
print(rs.loc["a":"c"])

#select column range 
print(rs.loc[:,'design':'development'])

#select alternative row 
print(rs.loc['a':'c':1])

#select alternative column
print(rs.loc[:,'development':'skills':2])

#using condioon0
rs.loc[rs['design'] >= 2]

a    24
b    35
c    66
dtype: int64
   design  development  skills
a       1            4      20
b       2            5      30
c       3            6      60
design          1
development     4
skills         20
Name: a, dtype: int64
a    4
b    5
Name: development, dtype: int64
   design  development  skills
a       1            4      20
c       3            6      60
   development  skills
a            4      20
b            5      30
c            6      60
   design  development  skills
a       1            4      20
b       2            5      30
c       3            6      60
   design  development
a       1            4
b       2            5
c       3            6
   design  development  skills
a       1            4      20
b       2            5      30
c       3            6      60
   development
a            4
b            5
c            6

   design  development  skills
b       2            5      30
c       3            6      60

Selection by integer location: Pandas iloc[]

Select Single Row & Column By Index - iloc

In [22]:
print(rs.iloc[1])

design          2
development     5
skills         30
Name: b, dtype: int64

select column by Index

In [23]:
rs.iloc[:,0]

a    1
b    2
c    3
Name: design, dtype: int64

Select Multiple Rows & Columns by Index

In [24]:
print(rs.iloc[0,2])

20

column

In [25]:
rs.iloc[:,[0,1,2]]

   design  development  skills
a       1            4      20
b       2            5      30
c       3            6      60

Select Columns between two Indexes

In [26]:
rs.iloc[:,1:4]

   development  skills
a            4      20
b            5      30
c            6      60

Select Alternate Rows

In [27]:
rs.iloc[0:2:2]

   design  development  skills
a       1            4      20

Select Alternate Columns

In [18]:
rs.iloc[:,0:2:2]

   design
a       1
b       2
c       3

using conditions

In [19]:
rs.iloc[list(rs['design'] >= 2)]

   design  development  skills
b       2            5      30
c       3            6      60

Addition of rows:

In [11]:
a1=pd.DataFrame([[10,12],[21,22]],columns=['a','b']) 
b1=pd.DataFrame([[33,44],[55,66]],columns=['a','b']) 
c1=[]
print(a1)
print(b1)

c1=pd.concat([a1,b1])
print("addtions of a1 + b1:",c1)

    a   b
0  10  12
1  21  22
    a   b
0  33  44
1  55  66
addtions of a1 + b1:     a   b
0  10  12
1  21  22
0  33  44
1  55  66

In [21]:
import pandas as pd  
a1=pd.DataFrame([[10,12],[21,22]],columns=['a','b']) 
b1=pd.DataFrame([[33,44],[55,66]],columns=['a','b']) 
print(a1) 
print(b1) 
c1=pd.concat([a1,b1])  
print(c1.drop(1))

    a   b
0  10  12
1  21  22
    a   b
0  33  44
1  55  66
    a   b
0  10  12
0  33  44

In [14]:
import pandas as pd 
a1=pd.DataFrame({'a':[12,13,45,67,89,90],'b':[21,22,89,76,5,34]}) 
b1=pd.DataFrame({'a':[410,420],'b':[310,320],'c':[220,330]}) 

a1.append(b1,ignore_index=True)

AttributeError: 'DataFrame' object has no attribute 'append'