1. Create a Series of numbers [10, 20, 30, 40, 50]. Print the Series.

In [1]:
import pandas as pd
import numpy as np

df=np.array([10, 20, 30, 40, 50])
sr=pd.Series(df)
print(sr)

0    10
1    20
2    30
3    40
4    50
dtype: int64

2. Create a Series with custom index: [100, 200, 300] and index ['a','b','c']

In [2]:
import pandas as pd
import numpy as np

df=np.array([100,200,300])
sr=pd.Series(df,index=['a','b','c'])
print(sr)

a    100
b    200
c    300
dtype: int64

3.Filter the Series to show elements greater than 25.

In [3]:
import pandas as pd
import numpy as np

df=np.array([15,10,20,25,40,47,60,100,200,300])
sr=pd.Series(df)
print(sr[sr>25])

4     40
5     47
6     60
7    100
8    200
9    300
dtype: int64

4.Create a Series [1, None, 3, None, 5] and fill missing values with 0.

In [40]:
import pandas as pd
import numpy as np

df=np.array([1, None, 3, None, 5] )
sr=pd.Series(df)
fl=sr.fillna(0)
print(fl)

0    1
1    0
2    3
3    0
4    5
dtype: int64

C:\Users\korat\AppData\Local\Temp\ipykernel_3448\1123629864.py:6: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  fl=sr.fillna(0)

5.Find the sum, mean, maximum, and minimum of a Series [5, 10, 15, 20, 25]

In [8]:
import pandas as pd
import numpy as np

df=np.array([5, 10, 15, 20, 25])
sr=pd.Series(df)
f1=sr.agg([np.sum,np.mean,np.max,np.min])
print(f1)

C:\Users\korat\AppData\Local\Temp\ipykernel_16168\4255633762.py:6: FutureWarning: The provided callable <function sum at 0x000001C42E48CEA0> is currently using Series.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  f1=sr.agg([np.sum,np.mean,np.max,np.min])
C:\Users\korat\AppData\Local\Temp\ipykernel_16168\4255633762.py:6: FutureWarning: The provided callable <function mean at 0x000001C42E48E2A0> is currently using Series.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  f1=sr.agg([np.sum,np.mean,np.max,np.min])
C:\Users\korat\AppData\Local\Temp\ipykernel_16168\4255633762.py:6: FutureWarning: The provided callable <function max at 0x000001C42E48D8A0> is currently using Series.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  f1=sr.agg([np.sum,np.mean,np.max,np.min])
C:\Users\korat\AppData\Local\Temp\ipykernel_16168\4255633762.py:6: FutureWarning: The provided callable <function min at 0x000001C42E48D9E0> is currently using Series.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  f1=sr.agg([np.sum,np.mean,np.max,np.min])

sum     75.0
mean    15.0
max     25.0
min      5.0
dtype: float64

6.Print all students with Marks greater than 90

In [42]:
import pandas as pd
import numpy as np

df=np.array([70,80,90,99,94,96,98,100])
sr=pd.Series(df)
print(sr[sr>90])

3     99
4     94
5     96
6     98
7    100
dtype: int64

7.Drop the column Grade from the DataFrame.

In [43]:
import pandas as pd

sr=pd.DataFrame({'grade':[70,80,90,99,94,96,98,100],'name':['A','B','C','D','E','F','G','H']})

dr=sr.drop(columns=['grade'],axis=1)

print("Before Drop",sr)
print("After Drop Grade",dr)

Before Drop    grade name
0     70    A
1     80    B
2     90    C
3     99    D
4     94    E
5     96    F
6     98    G
7    100    H
After Drop Grade   name
0    A
1    B
2    C
3    D
4    E
5    F
6    G
7    H

8.Sort the DataFrame by Age in ascending order.

In [ ]:
import pandas as pd

sr=pd.DataFrame({'age':[60,11,10,7,4,2,70,80,90,99,94,96,98,100],'name':['A','B','C','D','E','F','G','H','I','J','K','L','M','N']})
xu
dr=sr.sort_values(by='age',ascending=True)

dr

    age name
5     2    F
4     4    E
3     7    D
2    10    C
1    11    B
0    60    A
6    70    G
7    80    H
8    90    I
10   94    K
11   96    L
12   98    M
9    99    J
13  100    N

9.Group the DataFrame by Grade and find the average Marks.

In [ ]:
import pandas as pd
import numpy as np

data = {'Name': ['sachin', 'raj', 'virat', 'dhoni'],   
   'Percentage': [82, 98, 91, 87],   
   'grade': ['A', 'A+', 'A+', 'A']}  

df=pd.DataFrame(data)

gb=df.groupby('grade')

print(gb['Percentage'].agg(np.average))

grade
A     84.5
A+    94.5
Name: Percentage, dtype: float64

10.Filter the Series to show numbers divisible by 3.

In [4]:
import pandas as pd   
import numpy as np   

df=pd.Series([3,6,9,12,11,10,15,30])

filtered_df = df[df%3==0]
print(filtered_df)
# print(df)

0     3
1     6
2     9
3    12
6    15
7    30
dtype: int64

11.Create two Series [1,2,3,4,5] and [5,4,3,2,1]. Perform element-wise multiplication

In [47]:
import pandas as pd   
import numpy as np   

s1=pd.Series([1,2,3,4,5])
s2=pd.Series([5,4,3,2,1])
# mul=s1*s2
multiplication=s1.multiply(s2)
print(multiplication)

0    5
1    8
2    9
3    8
4    5
dtype: int64

12.Create a Series of 20 random integers between 1–100. Count numbers divisible by 5

In [48]:
import pandas as pd
import numpy as np
from numpy import random 
a = random.randint(1,100,size=(5,4))  
print(a)
df=pd.DataFrame(a)

div=df[df%5==0]
print(div)

[[39  6 86 31]
 [ 6 62 60 43]
 [40 29 32 55]
 [39 92 78  8]
 [36 76 93 33]]
      0   1     2     3
0   NaN NaN   NaN   NaN
1   NaN NaN  60.0   NaN
2  40.0 NaN   NaN  55.0
3   NaN NaN   NaN   NaN
4   NaN NaN   NaN   NaN

13.Create a DataFrame of 3 students with marks in 3 subjects. Add total and average columns

In [5]:
data={'name':['aice','bob','chgarlie'],
      'maths':[80,90,70],
      'english':[85,95,75],
      'science':[90,80,85]}

df=pd.DataFrame(data)

df['total_marks']=df[['maths','english','science']].sum(axis=1)
df['average_marks']=df[['maths','english','science']].mean(axis=1)

df

       name  maths  english  science  total_marks  average_marks
0      aice     80       85       90          255      85.000000
1       bob     90       95       80          265      88.333333
2  chgarlie     70       75       85          230      76.666667